version: '3'
services:
  mongo-csb:
    image: mongo:jammy
    container_name: mongo-csb
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:rw
    networks:
      - callspamblocker
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: csbtubui
      MONGO_DATABASE: call-spam-blocker
    restart: always
  api-csb:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo-csb
      - redis-csb
    networks:
      - callspamblocker
    environment:
      MONGOOSE_URI: mongodb://root:csbtubui@mongo-csb:27017/
      AUTHORIZATION_CODE: spambl0ckerAuthorization2k1rbyp0wer
      JWT_KEY: c56v1llA8er
      REDIS_URI: redis://csbtubui:re6ort5list@redis-csb:6379
    container_name: api-csb
    restart: unless-stopped
    volumes:
      - ../log-server-error/csb:/app/logs:rw
  redis-csb:
    image: redis:7.0.11
    container_name: redis-csb
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data:rw
    ports:
      - "6379:6379"
volumes:
  mongo-data:
  mongo-config:
  redis-data:
networks:
  callspamblocker:
    driver: bridge